"""
tests/test_custom_range_warmup_lookahead.py
=============================================
Verification suite for custom date range selection, warm-up data isolation,
and anti-lookahead guarantees in SMC Replay and Backtest Engine:

1. Warm-up isolation: Historical lookback candles generate zero trades prior to analysis_start.
2. Range independence: Backtesting range [T1, T2] yields 100% identical trades regardless of future trailing bars.
3. Timestamp causality: Structure and HTF events are strictly non-visible before confirmed_at.
4. Batch vs Replay determinism: Sequential build_replay_timeline output matches batch coordinator run.
"""

import unittest
import numpy as np
import pandas as pd

from smc.engine.backtest_adapter import (
    SMCBacktestCoordinator,
    HTFTimeline,
)
from smc.engine.execution import ExecutionConfig
from smc.models import StructureEvent
from engine.backtest_engine import BacktestEngine


class TestCustomRangeWarmupLookahead(unittest.TestCase):
    def setUp(self):
        np.random.seed(42)
        base_time = pd.Timestamp("2024-01-01 00:00:00", tz="UTC")
        self.times = [base_time + pd.Timedelta(minutes=15 * i) for i in range(400)]

        prices = [2000.0]
        for i in range(399):
            step = 0.4 + np.random.normal(0, 1.0) if i < 200 else -0.3 + np.random.normal(0, 1.0)
            prices.append(round(prices[-1] + step, 3))

        rows = []
        for i, (t, p) in enumerate(zip(self.times, prices)):
            spread = abs(np.random.normal(0.5, 0.2))
            c_open = p
            c_close = p + np.random.normal(0.1, 0.3)
            c_high = max(c_open, c_close) + spread
            c_low = min(c_open, c_close) - spread
            rows.append({
                "bar_index": i,
                "time": t,
                "open": round(c_open, 3),
                "high": round(c_high, 3),
                "low": round(c_low, 3),
                "close": round(c_close, 3),
                "volume": 120.0,
            })
        self.df = pd.DataFrame(rows)

        self.htf_events = [
            StructureEvent(
                index=15,
                time=self.times[50],
                event_type="BOS",
                direction="bullish",
                broken_swing_index=10,
                broken_swing_price=2005.0,
                close_price=2008.0,
                displacement=True,
                mode="swing",
            ),
            StructureEvent(
                index=120,
                time=self.times[220],
                event_type="CHoCH",
                direction="bearish",
                broken_swing_index=100,
                broken_swing_price=2025.0,
                close_price=2018.0,
                displacement=True,
                mode="swing",
            ),
        ]

    def test_range_independence(self):
        """
        Executing backtest over range [0, 250] must produce identical trades
        whether executed alone or when 150 future bars are appended.
        """
        df_short = self.df.iloc[:250].copy()
        df_full = self.df.copy()

        coordinator_short = SMCBacktestCoordinator(htf_events=self.htf_events, mode="smc_wave1")
        res_short = coordinator_short.run(df_short)

        coordinator_full = SMCBacktestCoordinator(htf_events=self.htf_events, mode="smc_wave1")
        res_full = coordinator_full.run(df_full)

        # Trades generated within first 250 bars must match exactly
        short_trades = [t for t in res_short.trades]
        full_trades_in_range = [t for t in res_full.trades if t.get("entry_bar", 0) < 250]

        self.assertEqual(len(short_trades), len(full_trades_in_range))
        for t_s, t_f in zip(short_trades, full_trades_in_range):
            self.assertEqual(t_s["entry_bar"], t_f["entry_bar"])
            self.assertEqual(t_s["direction"], t_f["direction"])
            self.assertAlmostEqual(t_s["entry_price"], t_f["entry_price"], places=2)

    def test_timeline_replay_parity(self):
        """
        Replay timeline generated by build_replay_timeline must match batch execution final trades.
        """
        coordinator = SMCBacktestCoordinator(htf_events=self.htf_events, mode="smc_wave1")
        batch_res = coordinator.run(self.df)

        coord_replay = SMCBacktestCoordinator(htf_events=self.htf_events, mode="smc_wave1")
        timeline_res = coord_replay.build_replay_timeline(self.df, start_idx=0, max_bars=400)

        timeline = timeline_res["timeline"]
        self.assertEqual(len(timeline), len(self.df))

        # Check candidate count determinism
        batch_decisions = batch_res.decisions
        timeline_decisions = [b["selector"]["action"] for b in timeline if "selector" in b and "action" in b["selector"]]
        self.assertEqual(len(batch_decisions), len(timeline_decisions))

    def test_causality_and_no_lookahead(self):
        """
        No event or active state at bar N may reference a bar index > N or a timestamp > bar N close.
        """
        coordinator = SMCBacktestCoordinator(htf_events=self.htf_events, mode="smc_wave1")
        res = coordinator.build_replay_timeline(self.df, start_idx=0, max_bars=400)
        timeline = res["timeline"]

        for bar_snap in timeline:
            b_idx = bar_snap["bar_index"]
            b_time = bar_snap["time"]

            # Active OBs must originate at or before bar_idx
            for ob in bar_snap["active_state"]["obs"]:
                if "source_event_index" in ob and ob["source_event_index"] is not None:
                    self.assertLessEqual(ob["source_event_index"], b_idx)

            # Active FVGs must originate at or before bar_idx
            for fvg in bar_snap["active_state"]["fvgs"]:
                if "time" in fvg and fvg["time"] is not None:
                    fvg_time = pd.Timestamp(fvg["time"])
                    cur_time = pd.Timestamp(b_time)
                    self.assertLessEqual(fvg_time, cur_time)

    def test_warmup_isolation_and_zero_trades(self):
        """
        Verify that warmup bars (idx < start_idx) generate ZERO trades,
        while SMC context (HTF bias, active OBs/FVGs, swings) is properly initialized.
        """
        coordinator = SMCBacktestCoordinator(htf_events=self.htf_events, mode="smc_wave1")
        # Run with start_idx=100 (first 100 bars are warmup)
        res_warmup = coordinator.run(self.df, start_idx=100)

        # Ensure no trade has entry_bar < 100
        for t in res_warmup.trades:
            self.assertGreaterEqual(t.get("entry_bar", 0), 100, f"Trade entered at bar {t.get('entry_bar')} during warmup (< 100)!")

        # Verify build_replay_timeline with start_idx=100 emits timeline starting at bar index 100
        coord_replay = SMCBacktestCoordinator(htf_events=self.htf_events, mode="smc_wave1")
        timeline_res = coord_replay.build_replay_timeline(self.df, start_idx=100, max_bars=200)

        timeline = timeline_res["timeline"]
        self.assertEqual(len(timeline), 200)
        self.assertEqual(timeline[0]["bar_index"], 100)
        # Check that active state (OBs/FVGs/bias) is populated at bar 100
        self.assertIn("active_state", timeline[0])

    def test_large_dataset_capacity_over_1500_bars(self):
        """
        Verify that replay and backtest can process dataset larger than 1,500 candles without truncation.
        """
        # Create synthetic dataset with 2,500 bars
        times_large = [pd.Timestamp("2024-01-01 00:00:00", tz="UTC") + pd.Timedelta(minutes=15 * i) for i in range(2500)]
        prices_large = [2000.0 + (i * 0.05) for i in range(2500)]
        rows_large = []
        for i, (t, p) in enumerate(zip(times_large, prices_large)):
            rows_large.append({
                "bar_index": i,
                "time": t,
                "open": round(p, 3),
                "high": round(p + 0.5, 3),
                "low": round(p - 0.5, 3),
                "close": round(p + 0.1, 3),
                "volume": 100.0,
            })
        df_large = pd.DataFrame(rows_large)

        coordinator = SMCBacktestCoordinator(mode="smc_wave1")
        timeline_res = coordinator.build_replay_timeline(df_large, start_idx=0, max_bars=2500)
        self.assertEqual(len(timeline_res["timeline"]), 2500)
        self.assertEqual(timeline_res["timeline"][-1]["bar_index"], 2499)

    def test_api_backtest_and_replay_metadata_contract(self):
        """
        Verify that POST /api/backtest and POST /api/replay/timeline return standard metadata fields:
        warmup_start, analysis_start, analysis_end, warmup_candles, analysis_candles, display_candles.
        """
        from fastapi.testclient import TestClient
        from server import app

        client = TestClient(app)

        # 1. Backtest API metadata contract
        payload_bt = {
            "timeframe": "M15",
            "strategy_id": "smc_wave1",
            "limit": 100,
            "warmup_bars": 20,
            "start_time": "2024-01-01 05:00:00",
            "end_time": "2024-01-02 00:00:00",
        }
        res_bt = client.post("/api/backtest", json=payload_bt)
        self.assertEqual(res_bt.status_code, 200)
        data_bt = res_bt.json()
        self.assertEqual(data_bt["status"], "success")
        self.assertIn("warmup_start", data_bt)
        self.assertIn("analysis_start", data_bt)
        self.assertIn("analysis_end", data_bt)
        self.assertIn("warmup_candles", data_bt)
        self.assertIn("analysis_candles", data_bt)
        self.assertIn("display_candles", data_bt)
        self.assertEqual(data_bt["warmup_candles"], 20)

        # 2. Replay timeline API metadata contract
        payload_replay = {
            "timeframe": "M15",
            "symbol": "XAUUSD",
            "strategy_id": "smc_wave1",
            "limit": 100,
            "warmup_bars": 20,
            "start_time": "2024-01-01 05:00:00",
            "end_time": "2024-01-02 00:00:00",
            "start_bar_index": 0,
            "end_bar_index": 50,
            "max_bars": 100,
        }
        res_rp = client.post("/api/replay/timeline", json=payload_replay)
        self.assertEqual(res_rp.status_code, 200)
        data_rp = res_rp.json()
        self.assertEqual(data_rp["status"], "success")
        self.assertIn("warmup_start", data_rp)
        self.assertIn("analysis_start", data_rp)
        self.assertIn("analysis_end", data_rp)
        self.assertIn("warmup_candles", data_rp)
        self.assertIn("analysis_candles", data_rp)
        self.assertIn("display_candles", data_rp)
        self.assertIn("total_timeline_bars", data_rp)
        self.assertEqual(data_rp["warmup_candles"], 20)

    def test_api_validation_rules(self):
        """
        Verify validation rules return HTTP 400 for invalid inputs:
        - start_time > end_time
        - end_bar_index < start_bar_index
        - warmup_bars > 20000
        """
        from fastapi.testclient import TestClient
        from server import app

        client = TestClient(app)

        # Invalid start > end time
        res1 = client.post("/api/replay/timeline", json={
            "timeframe": "M15",
            "start_time": "2024-01-05 00:00:00",
            "end_time": "2024-01-01 00:00:00",
        })
        self.assertEqual(res1.status_code, 400)
        self.assertIn("start_time không được lớn hơn end_time", res1.json()["detail"])

        # Invalid end_bar_index < start_bar_index
        res2 = client.post("/api/replay/timeline", json={
            "timeframe": "M15",
            "start_bar_index": 10,
            "end_bar_index": 5,
        })
        self.assertEqual(res2.status_code, 400)
        self.assertIn("end_bar_index không được nhỏ hơn start_bar_index", res2.json()["detail"])

        # Invalid warmup_bars > 20000 (Pydantic schema le=20000 or custom validator returns 400/422)
        res3 = client.post("/api/replay/timeline", json={
            "timeframe": "M15",
            "warmup_bars": 25000,
        })
        self.assertIn(res3.status_code, (400, 422))

    def test_timeline_bar_flags_and_relative_indexing(self):
        """
        Verify each bar in timeline contains is_warmup, is_analysis, is_displayed flags.
        """
        coordinator = SMCBacktestCoordinator(htf_events=self.htf_events, mode="smc_wave1")
        res = coordinator.build_replay_timeline(self.df, start_idx=50, max_bars=100)
        timeline = res["timeline"]

        self.assertGreater(len(timeline), 0)
        for b in timeline:
            self.assertIn("is_warmup", b)
            self.assertIn("is_analysis", b)
            self.assertIn("is_displayed", b)
            self.assertFalse(b["is_warmup"])
            self.assertTrue(b["is_analysis"])
            self.assertTrue(b["is_displayed"])


if __name__ == "__main__":
    unittest.main()


