"""
smc/engine/protocol.py
======================
StrategyTemplate Protocol and validation helpers for SMC Strategy Templates (T53.3).
"""

from __future__ import annotations

import re
from typing import Any, Protocol, runtime_checkable

from smc.engine.errors import StrategyValidationError
from smc.engine.models import CandidateSetup, StrategyContext, StrategyProfile

_STRATEGY_ID_RE = re.compile(r"^[A-Za-z0-9_.-]+$")


def validate_strategy_id(strategy_id: str) -> str:
    """
    Validate that strategy_id strictly satisfies the stable component grammar:
    - Must be a non-empty string.
    - Matches ^[A-Za-z0-9_.-]+$.
    - Contains no delimiter ':'.
    - Contains no leading or trailing whitespace.
    - Non-string types are strictly rejected.

    Parameters:
        strategy_id: The candidate strategy ID string.

    Returns:
        The validated strategy_id unchanged.

    Raises:
        StrategyValidationError: If strategy_id is invalid.
    """
    if not isinstance(strategy_id, str):
        raise StrategyValidationError(
            f"strategy_id must be a string, got {type(strategy_id).__name__}: {strategy_id}"
        )
    if not strategy_id:
        raise StrategyValidationError("strategy_id cannot be empty.")
    if strategy_id != strategy_id.strip():
        raise StrategyValidationError(
            f"strategy_id cannot contain leading or trailing whitespace: '{strategy_id}'"
        )
    if ":" in strategy_id:
        raise StrategyValidationError(
            f"strategy_id cannot contain delimiter ':': '{strategy_id}'"
        )
    if not _STRATEGY_ID_RE.match(strategy_id):
        raise StrategyValidationError(
            f"strategy_id contains invalid characters (allowed [A-Za-z0-9_.-]): '{strategy_id}'"
        )
    return strategy_id


@runtime_checkable
class StrategyTemplate(Protocol):
    """
    Protocol defining the contract for all SMC strategy templates (S01, S05, S09, ...).

    A strategy template:
    - Exposes a stable `strategy_id: str` matching `profile.strategy_id`.
    - Holds an immutable `profile: StrategyProfile`.
    - Implements `evaluate(context: StrategyContext) -> tuple[CandidateSetup, ...]`.
    - Implements `reset() -> None` to clear all internal runtime state.
    """

    strategy_id: str
    profile: StrategyProfile

    def evaluate(self, context: StrategyContext) -> tuple[CandidateSetup, ...]:
        """
        Evaluate the strategy against the provided StrategyContext as-of closed bar N.

        Parameters:
            context: The immutable StrategyContext snapshot at closed bar N.

        Returns:
            A tuple of CandidateSetup instances generated by this strategy (empty tuple if no setup).

        Raises:
            Exception: Any unexpected domain or evaluation failure (must propagate, never swallowed).
        """
        ...

    def reset(self) -> None:
        """
        Reset all internal state machine tracking, caches, and pending setups of the strategy.
        Guarantees that replaying the same sequence of contexts produces identical results.
        """
        ...


def validate_strategy_template(strategy: Any) -> None:
    """
    Validate that an object strictly satisfies the StrategyTemplate contract.

    Validation rules:
    1. Must have attributes: strategy_id, profile, evaluate, reset.
    2. strategy_id must pass validate_strategy_id.
    3. profile must be an instance of StrategyProfile.
    4. strategy.strategy_id == strategy.profile.strategy_id.
    5. evaluate must be callable.
    6. reset must be callable.

    Parameters:
        strategy: Any candidate strategy object.

    Raises:
        StrategyValidationError: If the strategy violates any contract invariant.
    """
    for attr in ("strategy_id", "profile", "evaluate", "reset"):
        if not hasattr(strategy, attr):
            raise StrategyValidationError(
                f"Strategy object does not satisfy StrategyTemplate protocol: missing '{attr}'."
            )

    validate_strategy_id(strategy.strategy_id)

    if not isinstance(strategy.profile, StrategyProfile):
        raise StrategyValidationError(
            f"Field 'profile' must be a StrategyProfile, got {type(strategy.profile).__name__}."
        )

    if strategy.strategy_id != strategy.profile.strategy_id:
        raise StrategyValidationError(
            f"Strategy strategy_id '{strategy.strategy_id}' does not match "
            f"profile.strategy_id '{strategy.profile.strategy_id}'."
        )

    if not callable(strategy.evaluate):
        raise StrategyValidationError("Field 'evaluate' must be callable.")

    if not callable(strategy.reset):
        raise StrategyValidationError("Field 'reset' must be callable.")


__all__ = [
    "StrategyTemplate",
    "validate_strategy_id",
    "validate_strategy_template",
]
